### PR TITLE
Smooth animation for scrollToTop and scrollToBottom actions

### PR DESCRIPTION
**Pull request by emvaized**
I haven't tested it on a phone, but it probably should work just fine.

### CODE REVIEW

**Comment by KristhianX** [comment]
Hi! I’m really happy to see your interest in improving this add-on. Thanks! :)

At the moment, I don’t have access to my computer, so I’m unable to make changes to the add-on or test them. I did, however, test your code using the [userscript](https://github.com/KristhianX/a-real-home-button) version of the add-on and didn’t notice any difference in the scroll animation. Could you please test the code on your end and let me know if it works as expected? If so, I’ll go ahead and merge it, then submit an update.

**Comment by emvaized** [comment]
> and didn’t notice any difference in the scroll animation

Hm, that's weird. Maybe you have smooth scrolling disabled in your Firefox? Maybe in `about:config` flags? Because I just checked, and the scroll `behavior` option is [supported](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo#browser_compatibility) in Firefox Android.

Does the animation work for you in this [example code](https://stackoverflow.com/a/58214149) from Stackoverflow, which utilizies the same method? It works for me on Firefox Android v.130

**Comment by KristhianX** [comment]
I tested the example code on Fennec F-Droid, Firefox Nightly, Iceraven, and the latest Firefox from the Play Store, but none of them applied the smooth scroll behavior. I also tested it with a Chromium-based browser, and it correctly displayed the animation. I have no idea what might be wrong with my phone, but it's likely the code will work for most users.

I will merge the pull request and publish an update in the store. Thanks for your contribution!

**Comment by emvaized** [comment]
Thanks for accepting my PR!

> I tested the example code on Fennec F-Droid, Firefox Nightly, Iceraven, and the latest Firefox from the Play Store, but none of them applied the smooth scroll behavior

That's weird! My only explanation would be some system settings to reduce animations  as I consistently got it to work in both stable Firefox and Firefox Nightly. 

> it's likely the code will work for most users

Well, at least it shouldn't break anything🤞

**Comment by KristhianX** [comment]
> That's weird! My only explanation would be some system settings to reduce animations

You were right, I had animations disabled in the accessibility settings on Android. Now I can see the animations. 

The update is already approved in the Mozilla store, and it’s working perfectly. Thanks!

**Pull request merged**
